### ISSUE TITLE
Problem Homebridge Samsung Air Conditioner Smartthings

### ISSUE THREAD

**Issue by slaw47** [teodoradima/homebridge-samsung-air-conditioner-smart-things#26]
**Describe Your Problem:**

**Logs:**

```
[08/11/2023, 13:31:57] [homebridge-samsung-air-conditioner-smart-things] This plugin slows down Homebridge. The read handler for the characteristic 'Active' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by slaw47** [comment]
Today:
[09/11/2023, 06:12:12] [homebridge-samsung-air-conditioner-smart-things] Error: Request failed with status code 500
    at createError (/var/lib/homebridge/node_modules/homebridge-samsung-air-conditioner-smart-things/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/lib/homebridge/node_modules/homebridge-samsung-air-conditioner-smart-things/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-samsung-air-conditioner-smart-things/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
